### ISSUE TITLE
Files on client side?

### ISSUE THREAD

**Issue by m4v15** [FACN1/week4-D-REEM-TEAM#41]
You've put render/eventlistener/request functions in different files 🗄  on the client side, but none if it is actually modularised? I guess this still separates 🗂  out the code for readability 📖  but everything is global 🌏  and accessible which could cause issues.

For example: 

```var inputField = document.getElementById('autoCompleteInput');```

this line appears [here](https://github.com/FACN1/week4-D-REEM-TEAM/blob/master/public/render.js#L2) and[here](https://github.com/FACN1/week4-D-REEM-TEAM/blob/master/public/userListener.js#L1). In this case they are exactly the same so one is redundant, but if the variable name 📛  was the same you would probably run 🏃  into trouble somewhere.

**Comment by edgarfinn** [comment]
🌾

**Comment by macintoshhelper** [comment]
Fixed in 3 commits. The last fix commit: 3dffab7262a0987bb5d14cb930b2b6ae76ec90a2 .

**Comment by m4v15** [comment]
Looking good 👀  👍
